formset_factory/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('invoicing.urls', namespace='invoicing')),
]

invoicing/urls.py
from django.conf.urls import url

from invoicing.views import InvoiceSingleTableView, InvoiceFormView, InvoiceUpdateView

urlpatterns = [
    url(r'^$', InvoiceSingleTableView.as_view(), name='invoice_list'),
    url(r'^new-invoice/$', InvoiceFormView.as_view(), name='invoice_add'),
    url(r'^edit-invoice/(?P<pk>\d+)/$$', InvoiceUpdateView.as_view(), name='invoice_edit'),
]

invoicing/models.py
from django.core.urlresolvers import reverse
from django.db import models


class Customer(models.Model):
    name = models.CharField('name', max_length=255)

    def __str__(self):
        return self.name


class Invoice(models.Model):
    customer = models.ForeignKey(Customer)
    total = models.IntegerField('Total')

    created = models.DateTimeField('created', auto_now_add=True)
    modified = models.DateTimeField('modified', auto_now=True)

    def get_absolute_url(self):
        return reverse('invoicing:invoice_detail', args=(self.pk,))


class Item(models.Model):
    invoice = models.ForeignKey(Invoice)
    title = models.CharField('title', max_length=255)
    quantity = models.DecimalField('quantity', max_digits=10, decimal_places=3, default=1)
    unit_price = models.DecimalField('unit price', max_digits=10, decimal_places=2)

    created = models.DateTimeField('created', auto_now_add=True)
    modified = models.DateTimeField('modified', auto_now=True)

invoicing/forms.py
from django import forms
from django.forms import formset_factory, modelformset_factory

from invoicing.models import Invoice, Item


class InvoiceForm(forms.ModelForm):
    class Meta:
        model = Invoice
        exclude = ['total', 'created', 'modified']


class ItemForm(forms.ModelForm):
    class Meta:
        model = Item
        exclude = ['invoice', 'created', 'modified']


ItemInvoiceFormSet = formset_factory(ItemForm, min_num=1, validate_min=True, extra=0, max_num=16, validate_max=True)

ItemInvoiceUpdateFormSet = modelformset_factory(Item, form=ItemForm, min_num=1, validate_min=True, extra=0,
                                                can_delete=True, max_num=16, validate_max=True)

invoicing/views.py
from django.contrib.messages.views import SuccessMessageMixin
from django.urls import reverse_lazy
from django.views.generic import FormView, UpdateView
from django_tables2 import SingleTableView

from invoicing.forms import InvoiceForm, ItemInvoiceFormSet, ItemInvoiceUpdateFormSet
from invoicing.models import Invoice
from invoicing.tables import InvoiceTable


class InvoiceFormView(SuccessMessageMixin, FormView):
    form_class = InvoiceForm
    template_name = 'invoice_form.html'
    success_url = reverse_lazy('invoicing:invoice_list')
    success_message = 'The invoice was created correctly.'

    def get_context_data(self, **kwargs):
        context = super(InvoiceFormView, self).get_context_data(**kwargs)
        if self.request.POST:
            context['formset'] = ItemInvoiceFormSet(self.request.POST, prefix='items')
        else:
            context['formset'] = ItemInvoiceFormSet(prefix='items')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        total = 0
        if formset.is_valid():
            invoice = form.save(commit=False)
            invoice.total = 0
            invoice.save()
            for item_form in formset.forms:
                item = item_form.save(commit=False)
                item.invoice = invoice
                item.save()
                total += item.quantity * item.unit_price
            invoice.total = total
            invoice.save()
            return super(InvoiceFormView, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class InvoiceUpdateView(SuccessMessageMixin, UpdateView):
    model = Invoice
    form_class = InvoiceForm
    template_name = 'invoice_edit.html'
    success_url = reverse_lazy('invoicing:invoice_list')
    success_message = 'The invoice was edited correctly.'

    def get_context_data(self, **kwargs):
        context = super(InvoiceUpdateView, self).get_context_data(**kwargs)
        invoice = self.get_object()
        productos = invoice.item_set.all()
        if self.request.POST:
            context['formset'] = ItemInvoiceUpdateFormSet(self.request.POST, self.request.FILES, prefix='items')
        else:
            context['formset'] = ItemInvoiceUpdateFormSet(queryset=productos, prefix='items')
        return context

    def form_valid(self, form):
        context = self.get_context_data()
        formset = context['formset']
        total = 0
        if formset.is_valid():
            invoice = form.save(commit=False)
            for item_form in formset.forms:
                item = item_form.save(commit=False)
                item.invoice = self.get_object()
                item.save()
                total += item.quantity * item.unit_price
            formset.save()
            invoice.total = total
            invoice.save()
            return super(InvoiceUpdateView, self).form_valid(form)
        else:
            return self.render_to_response(self.get_context_data(form=form))


class InvoiceSingleTableView(SingleTableView):
    table_class = InvoiceTable
    queryset = Invoice.objects.all()
    template_name = 'invoice_list.html'

invoicing/templates/invoice_edit.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
  <div class="col-md-12">
    <p>
      <a href="{% url 'invoicing:invoice_list' %}" class="btn btn-primary">Invoice list</a>
    </p>
  </div>
  <br>
  <div class="col-lg-12">
    <h2>Edit Invoice</h2>
    <br>
    {% bootstrap_form_errors form %}

    {% bootstrap_formset_errors formset %}

    <form method="post" role="form" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form_errors form %}
    {% bootstrap_formset_errors formset %}
      <fieldset>
        {% bootstrap_form form %}
      </fieldset>
      <fieldset>
        <table class="table">
          <thead>
          <th>Title</th>
          <th>Quantity</th>
          <th>Unit price</th>
          <th></th>
          </thead>
          {{ formset.management_form }}
          <tbody>
          {% for item_form in formset.forms %}
            {% for hidden in item_form.hidden_fields %}
              {{ hidden }}
            {% endfor %}
            <tr class="formset">
              <td class="col-md-8">{% bootstrap_field item_form.title show_label=False %}</td>
              <td class="col-md-2">{% bootstrap_field item_form.quantity show_label=False %}</td>
              <td class="col-md-2">{% bootstrap_field item_form.unit_price show_label=False %}</td>
              <td class=""></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </fieldset>
      <br><br>
      {% buttons %}
        <button type="submit" class="btn btn-primary pull-right">Edit invoice</button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/jquery.formset.min.js' %}"></script>
  <script src="{% static 'js/invoice_form.js' %}"></script>
{% endblock %}

invoicing/templates/invoice_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}

{% block content %}
  <div class="col-md-12">
    <p>
      <a href="{% url 'invoicing:invoice_list' %}" class="btn btn-primary">Invoice list</a>
    </p>
  </div>
  <br>
  <div class="col-lg-12">
    <h2>New Invoice</h2>
    <br>
    {% bootstrap_form_errors form %}

    {% bootstrap_formset_errors formset %}

    <form method="post" role="form" autocomplete="off" enctype="multipart/form-data">{% csrf_token %}
    {% bootstrap_form_errors form %}
    {% bootstrap_formset_errors formset %}
      <fieldset>
        {% bootstrap_form form %}
      </fieldset>
      <fieldset>
        <table class="table">
          <thead>
          <th>Title</th>
          <th>Quantity</th>
          <th>Unit price</th>
          <th></th>
          </thead>
          {{ formset.management_form }}
          <tbody>
          {% for item_form in formset.forms %}
            <tr class="formset">
              <td class="col-md-8">{% bootstrap_field item_form.title show_label=False %}</td>
              <td class="col-md-2">{% bootstrap_field item_form.quantity show_label=False %}</td>
              <td class="col-md-2">{% bootstrap_field item_form.unit_price show_label=False %}</td>
              <td class=""></td>
            </tr>
          {% endfor %}
          </tbody>
        </table>
      </fieldset>
      <br><br>
      {% buttons %}
        <button type="submit" class="btn btn-primary pull-right">Create invoice</button>
      {% endbuttons %}
    </form>
  </div>
{% endblock %}

{% block js %}
  <script src="{% static 'js/jquery.formset.min.js' %}"></script>
  <script src="{% static 'js/invoice_form.js' %}"></script>
{% endblock %}

invoicing/templates/invoice_list.html
{% extends 'base.html' %}
{% load staticfiles %}
{% load bootstrap3 %}
{% load render_table from django_tables2 %}

{% block content %}
  <div class="col-md-12">
    <p>
      <a href="{% url 'invoicing:invoice_add' %}" class="btn btn-primary">New invoice</a>
    </p>
  </div>
  <br>
  <div class="col-md-12">
    {% render_table table %}
  </div>
{% endblock %}

templates/base.html
{% load staticfiles %}
{% load bootstrap3 %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">
  <link rel="icon" href="../../favicon.ico">

  <title>formset_factory</title>

<!-- Latest compiled and minified CSS -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
<!-- Optional theme -->
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous"></head>

<body>
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading">Django formset_factory example</h1>
  </div>
</section>

<div class="album text-muted">
  <div class="container">
  {% bootstrap_messages %}
    <div class="row">
      {% block content %}{% endblock %}
    </div>
  </div>
</div>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<!-- Latest compiled and minified JavaScript -->
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
{% block js %}{% endblock %}
</body>
</html>